### ISSUE TITLE
Intermittent internal error when calling synthetize_speech

### ISSUE THREAD

**Issue by juanitosvq** [googleapis/python-texttospeech#48]
Hi there,

We are using the texttospeech API, and very intermittently we receive a 500 error. We were trying to synthesize a piece of text with 4 characters. See below version of the library and stacktrace. Apologies if this is not the right place to ask, let me know if you need further information.

Thanks in advance!

#### Environment details
    google-cloud-texttospeech 1.0.1
    python3.7

#### Code example

```python
google_voice = texttospeech.types.VoiceSelectionParams(language_code="en-US", name="en-US-Wavenet-C")
audio_config = texttospeech.types.AudioConfig(
  audio_encoding=texttospeech.enums.AudioEncoding.LINEAR16,
  sample_rate_hertz=48000,
)

response = get_google_client().synthesize_speech(
    texttospeech.types.SynthesisInput(text="test"), google_voice, audio_config
)
```

#### Stack trace
```
Traceback (most recent call last):
File "/var/task/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
return callable_(*args, **kwargs)
File "/var/task/grpc/_channel.py", line 826, in __call__
return _end_unary_response_blocking(state, call, False, None)
File "/var/task/grpc/_channel.py", line 729, in _end_unary_response_blocking
raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.INTERNAL
details = "Internal error encountered."
debug_error_string = "{"created":"@1591302346.428948598","description":"Error received from peer ipv4:REDACTED","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Internal error encountered.","grpc_status":13}"
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/var/task/validation.py", line 221, in validate_task
create_segments(segments)
File "/var/task/validation.py", line 187, in create_segments
create_segment_internal(segment, voice)
File "/var/task/segments.py", line 147, in synthesize_speech
texttospeech.types.SynthesisInput(text=segment.text), google_voice, audio_config
File "/var/task/google/cloud/texttospeech_v1/gapic/text_to_speech_client.py", line 322, in synthesize_speech
request, retry=retry, timeout=timeout, metadata=metadata
File "/var/task/google/api_core/gapic_v1/method.py", line 143, in __call__
return wrapped_func(*args, **kwargs)
File "/var/task/google/api_core/retry.py", line 286, in retry_wrapped_func
on_error=on_error,
File "/var/task/google/api_core/retry.py", line 184, in retry_target
return target()
File "/var/task/google/api_core/timeout.py", line 214, in func_with_timeout
return func(*args, **kwargs)
File "/var/task/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
six.raise_from(exceptions.from_grpc_error(exc), exc)
File "<string>", line 3, in raise_from
google.api_core.exceptions.InternalServerError: 500 Internal error encountered.
```

**Comment by munkhuushmgl** [comment]
Hmm, I was not able to reproduce the this error with your info and steps provided.
I need a bit more info about `Intermittent internal `

It worked as it intended for me. 
Here is my code I have used. I added some code to write out output as mp3 on top of your code snippet.

1. python3.7
2. google-cloud-texttospeech 1.0.1 (Note: latest version 2.0.0)

```

from google.cloud import texttospeech

google_voice = texttospeech.types.VoiceSelectionParams(language_code="en-US", name="en-US-Wavenet-C")
audio_config = texttospeech.types.AudioConfig(
    audio_encoding=texttospeech.enums.AudioEncoding.LINEAR16,
    sample_rate_hertz=48000,
)
client = texttospeech.TextToSpeechClient()

response = client.synthesize_speech(
    texttospeech.types.SynthesisInput(text="test"), google_voice, audio_config
)

# added code to test output
# The response's audio_content is binary.
with open("output.mp3", "wb") as out:
    out.write(response.audio_content)
    print('Audio content written to file "output.mp3"')
```

**Comment by munkhuushmgl** [comment]
It may not be speech client's issue, looks like it is more related to network and gRPC

https://github.com/grpc/grpc/issues/16515

**Comment by juanitosvq** [comment]
Unfortunately it's something which happens intermittently, so it's hard to provide any more information. But it sounds, by looking at the issue you copied, like we will have to implement our own retry mechanism here. 

Thanks for looking into this so promptly.

Closing since it looks like it's not an issue with `python-texttospeech`
