### ISSUE TITLE
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses

### ISSUE THREAD

**Issue by sfbby** [googleapis/python-texttospeech#83]
**my emv:**
google-cloud-texttospeech-1.0.1
 google-cloud-texttospeech 2.2.0

**my eror**
 0%|                                                                                            | 0/1 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "E:\soft\Anaconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "E:\soft\Anaconda3\lib\site-packages\grpc\_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "E:\soft\Anaconda3\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1597845921.934000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4090,"referenced_errors":[{"created":"@1597845921.934000000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "newdemo.py", line 43, in <module>
    response = client.synthesize_speech(synthesis_input, voice, audio_config)
  File "E:\soft\Anaconda3\lib\site-packages\google\cloud\texttospeech_v1\gapic\text_to_speech_client.py", line 321, in synthesize_speech
    return self._inner_api_calls["synthesize_speech"](
  File "E:\soft\Anaconda3\lib\site-packages\google\api_core\gapic_v1\method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "E:\soft\Anaconda3\lib\site-packages\google\api_core\retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "E:\soft\Anaconda3\lib\site-packages\google\api_core\retry.py", line 184, in retry_target
    return target()
  File "E:\soft\Anaconda3\lib\site-packages\google\api_core\timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "E:\soft\Anaconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses

please tell me ,How to solve this bug?

**Comment by munkhuushmgl** [comment]
@sfbby Hello, Would you please share your code snippet you used?

**Comment by DonFlymoor** [comment]
Hi! I'm having the same problem. Here is the code snippet I used:
```python
"""Synthesizes speech from the input string of text or ssml.

Note: ssml must be well-formed according to:
    https://www.w3.org/TR/speech-synthesis/
"""
from google.cloud import texttospeech

# Instantiates a client
client = texttospeech.TextToSpeechClient()

# Set the text input to be synthesized
synthesis_input = texttospeech.SynthesisInput(text="Hello, World!")

# Build the voice request, select the language code ("en-US") and the ssml
# voice gender ("neutral")
voice = texttospeech.VoiceSelectionParams(
    language_code="en-US", ssml_gender=texttospeech.SsmlVoiceGender.NEUTRAL
)

# Select the type of audio file you want returned
audio_config = texttospeech.AudioConfig(
    audio_encoding=texttospeech.AudioEncoding.MP3
)

# Perform the text-to-speech request on the text input with the selected
# voice parameters and audio file type
response = client.synthesize_speech(
    input=synthesis_input, voice=voice, audio_config=audio_config
)

# The response's audio_content is binary.
with open("output.mp3", "wb") as out:
    # Write the response to the output file.
    out.write(response.audio_content)
    print('Audio content written to file "output.mp3"')
```

And the output:
```python
E0921 16:37:53.489000000 12716 src/core/tsi/ssl_transport_security.cc:1439] Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.
Traceback (most recent call last):
  File "C:\Users\Don\Documents\Miniconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "C:\Users\Don\Documents\Miniconda3\lib\site-packages\grpc\_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\Don\Documents\Miniconda3\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1600720673.734000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4090,"referenced_errors":[{"created":"@1600720673.734000000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Don\Documents\Python\voxtalkz\cloudttstest.py", line 28, in <module>
    input=synthesis_input, voice=voice, audio_config=audio_config
  File "C:\Users\Don\Documents\Miniconda3\lib\site-packages\google\cloud\texttospeech_v1\services\text_to_speech\client.py", line 374, in synthesize_speech
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "C:\Users\Don\Documents\Miniconda3\lib\site-packages\google\api_core\gapic_v1\method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\Don\Documents\Miniconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses
```

**Comment by munkhuushmgl** [comment]
@DonFlymoor Looks like it is more related to auth not specifically tied to texttospeech library

**Comment by munkhuushmgl** [comment]
Closing this due to inactivity,

If you believe that part of this issue still needs to be addressed in this client library, then feel free to re-open this issue with more information.
